source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'wscLib_Example' do
  pod 'wscLib', :path => '../'

  target 'wscLib_Tests' do
    inherit! :search_paths

    pod 'SAMKeychain', '~> 1.5.3'
#    pod 'FBSnapshotTestCase'
  end
end
